# Generated by Django 2.2.7 on 2019-11-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clustercredentials',
            options={'verbose_name_plural': 'Cluster credentials'},
        ),
        migrations.AlterModelOptions(
            name='infobasecredentials',
            options={'verbose_name_plural': 'Infobase credentials'},
        ),
        migrations.CreateModel(
            name='HostCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_credentials', to='clusterconfig.Host')),
            ],
            options={
                'verbose_name_plural': 'Host credentials',
            },
        ),
    ]
