# Generated by Django 2.2.7 on 2019-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterconfig', '0002_auto_20191115_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustercredentials',
            name='pwd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostcredentials',
            name='pwd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='infobasecredentials',
            name='login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='infobasecredentials',
            name='pwd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
