# Generated by Django 2.2.7 on 2019-11-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterconfig', '0003_auto_20191115_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clustercredentials',
            options={'verbose_name': 'Cluster credentials', 'verbose_name_plural': 'Cluster credentials'},
        ),
        migrations.AlterModelOptions(
            name='hostcredentials',
            options={'verbose_name': 'Host credentials', 'verbose_name_plural': 'Host credentials'},
        ),
        migrations.AlterModelOptions(
            name='infobasecredentials',
            options={'verbose_name': 'Infobase credentials', 'verbose_name_plural': 'Infobase credentials'},
        ),
        migrations.CreateModel(
            name='InfobaseDefaultCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100)),
                ('pwd', models.CharField(blank=True, max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infobase_default_credentials', to='clusterconfig.Cluster')),
            ],
            options={
                'verbose_name': 'Infobase default credentials',
                'verbose_name_plural': 'Infobase default credentials',
            },
        ),
    ]
